### ISSUE TITLE
aggregator cannot crawl "-deactivated" blogs

### ISSUE THREAD

**Issue by najisawas** [monotony113/feedly-stream-reader#1]
not sure if this is an issue but just wanted to bring it up because this tool is supposed to help with "dead" blogs:

when a user deactivates their account the `BLOG_NAME.tumblr.com` becomes unavailable (unless newly registered) and the account name is tagged as deactivated (ie. `bommieluv84` --> `bommieluv84-deactivated20191202`)

calling the crawler works with currently active blogs but cannot find the rss feed for blogs that have been deactivated. 
`Cannot find a feed from Feedly using the query http://bommieluv84-deactivated20191202.tumblr.com/rss`

Is this expected?

awesome job with this project btw!

**Comment by tonywu7** [comment]
I tried searching a few deactivated blogs using Feedly

Essentially, Feedly cannot retrieve data from a blog once it it was deactivated. However, Feedly may have data from a blog _before_ it was deactivated, which will then be available under a domain name without `-deactivated`.

And so to crawl a deactivated blog, your best bet is to try the URL without the `-deactivated` part. But if both the domain name with and without `-deactivated` return results on Feedly, then most likely the one with `-deactivated` is the original blog, and the one without
is a new blog using a recycled name.

----

There seem to be a few scenarios:

- Neither of the domains is accessible on Tumblr, and neither returns any result on Feedly.

    Example: `bommieluv84-deactivated20191202.tumblr.com`.

    In this case, most likely, no one has ever subscribed to the blog on Feedly even when it was still active, hence Feedly doesn't have any data from it.

- Neither of the domains is accessible on Tumblr, but the domain name without `-deactivated` returns items on Feedly

    Example: `plumski-deactivated20140129.tumblr.com` => [Feedly API Query](https://cloud.feedly.com/v3/streams/contents?streamId=feed/http://plumski.tumblr.com/rss&count=1&ranked=oldest)

    This means people have subscribed to this blog on Feedly, and Feedly likely has all the posts up to the point it was deactivated.

    Example 2: `castronomicaaal-deactivated2019.tumblr.com` => [Feedly API Query](https://cloud.feedly.com/v3/streams/contents?streamId=feed/http://castronomicaaal.tumblr.com/rss&count=1&ranked=oldest)

    Here the blog was deactivated but then recycled by Tumblr and was registered by a new user. You can tell by the fact that posts from [castronomicaaal.tumblr.com](https://castronomicaaal.tumblr.com/archive) dates back to 2019 but there [exists a blog post under the same username](https://bernthalus-christ.tumblr.com/post/106106038913/castronomicaaal-deactivated2019-i-adore-the) back in 2014.

- Rarely, both the domain name with and without `-deactivated` return results on Feedly. This could either mean that the blog wasn't actually deleted, but the user merely added the `-deactivated` part themselves to their account name (e.g. [`capitalco-deactivated.tumblr.com`](https://capitalco-deactivated.tumblr.com/)), or it could be that Tumblr did not fully deactivate the blog, judging by the fact that their archive page and RSS feed are still available (e.g. [`fairygif-deactivated2015.tumblr.com`](https://fairygif-deactivated2015.tumblr.com/archive), in this example the blog name was also recycled).

----

Btw, I just released an update. Among other features, it allows you to define URL templates using a Python file:

```python
FEED_TEMPLATES = {
    r'.*\.tumblr\.com/?.*': {
        'http://%(netloc)s/rss': 100,
        'http://%(netloc)s/rss#_=_': 200,
        'https://%(netloc)s/rss': 300,
        'https://%(netloc)s/rss#_=_': 400,
    },
}
```

Then, instead of having to specify the full URL, you can just specify `http://blog.tumblr.com` and it will try possible feed URLs (`http://blog.tumblr.com/rss`, `https://blog.tumblr.com/rss`, ...) for you. I've now [added templates specific to deactivated blogs](https://github.com/monotony113/feedly-link-aggregator/blob/fdb350a67d0f42f817da83ce6030b122a19fba49/presets/tumblr.py#L12-L22) to the Tumblr preset.
